# NOTE: this file is generated via 'make generate'
bug:
  - 'panic:'
crash:
  - 'panic:'
feature/administrative-units:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_administrative_unit((.|\n)*)###'

feature/app-role-assignments:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_app_role_assignment((.|\n)*)###'

feature/applications:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_application((.|\n)*)###'

feature/conditional-access:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_(conditional_access_policy|named_location)((.|\n)*)###'

feature/directory-objects:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_directory_object((.|\n)*)###'

feature/directory-roles:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_(custom_directory_role|directory_role)((.|\n)*)###'

feature/domains:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_domains((.|\n)*)###'

feature/groups:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_(group\W+|group_member\W+|groups\W+)((.|\n)*)###'

feature/identity-governance:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_(access_package|privileged_access_group_)((.|\n)*)###'

feature/invitations:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_invitation((.|\n)*)###'

feature/policies:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_(authentication_strength_policy|claims_mapping_policy|group_role_management_policy)((.|\n)*)###'

feature/service-principals:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_(client_config|service_principal)((.|\n)*)###'

feature/synchronization:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_synchronization_((.|\n)*)###'

feature/user-flows:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_user_flow_attribute((.|\n)*)###'

feature/users:
  - '### (|New or )Affected Resource\(s\)\/Data Source\(s\)((.|\n)*)azuread_(user\W+|users\W+)((.|\n)*)###'
