# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

run:
  timeout: 20m
  modules-download-mode: vendor
  skip-files:
    - "internal/services/.*/.*_gen.go$"

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - reassign
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - govet
    - vetshadow

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set|Clear,fmt:.*,io:Close
  nakedret:
    max-func-lines: 40
