dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - "1.12.x"

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- make tools

env:
  matrix:
    - MODE=unit-tests
    - MODE=linters
    - MODE=website

script:
  - if [[ $MODE == 'unit-tests' ]]; then make test; fi
  - if [[ $MODE == 'linters' ]]; then make lint; fi
  - if [[ $MODE == 'website' ]]; then make website-test; fi
