---
name: GoLang Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/golint.yaml'
      - 'vendor/**'
      - '**.go'

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: .go-version
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: 'v2.12.2'
          args: ./...

  save-artifacts-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml@latest
