#---
#name: Terraform Schema Linting
#on:
#  pull_request:
#    types: ['opened', 'synchronize']
#    paths:
#      - '**.go'
#      - 'vendor/**'
#      - '.github/workflows/**'
#
#jobs:
#  go-version:
#    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.go-version.outputs.version }}
#    steps:
#      - uses: actions/checkout@v2
#
#      - id: go-version
#        run: echo "::set-output name=version::$(cat ./.go-version)"
#
#  tflint:
#    needs: go-version
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-go@v2
#        with:
#          go-version: '${{ needs.go-version.outputs.version }}'
#      - run: bash scripts/gogetcookie.sh
#      - run: make tools
#      - run: make tflint
