---
name: 32 Bit Build

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/thirty-two-bit.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'thirtytwo-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  compatibility-32bit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: GOARCH=386 GOOS=linux go build -o 32bitbuild .
